#!/usr/bin/env bash

# opens psql on db and connects to dev database
function l_db(){
	docker exec -it $(docker-compose ps -q census-db) su postgres -c "psql census_dev"
}

# given a service prefix(eg: db) it will execute bash on it
function l_bash(){
	docker exec -it $(docker-compose ps -q census-$1) bash
}