---
swagger: "2.0"
info:
  description: "US Census exercise API"
  version: "1.0.0"
  title: "Census API"
host: "localhost:3000"
basePath: "/census"
schemes:
  - "http"
produces:
  - "text/html"
  - "application/json"
paths:
  /ping:
    get:
      summary: Performs a sanity check
      description: Just a test
      responses:
        200:
          description: just a sanity check
  /by/{id}:
    get:
      produces:
      - "application/json"
      summary: Statistics by category
      description: It will returns items sumarized by given category with item count and average age
      parameters:
        - name: "id"
          in: "path"
          description: 
            "Id of the requested category (0-40): class of worker, industry code, occupation code, education, wage per hour, last education, marital status, major industry code, major occupation code, mace, hispanice, sex, member of labor, reason for unemployment, fulltime, capital gain, capital loss, dividends, income tax liability, previous residence region, previous residence state, household-with-family, household-simple, weight, msa-change, reg-change, within-reg-change, lived-here, migration prev res in sunbelt, num persons worked for employer, family members under 118, father birth country, mother birth country, birth country, citizenship, own business or self employed, fill questionnaire for veteran's admin, veterans benefits, weeks worked in year, year, salary range"
          required: true
          type: "integer"
      responses:
        200:
          description: Items corespoding to the given category