exports.seed = (knex, Promise) => {
  return knex('census').del()
  .then(() => {
    return Promise.join(
      knex('census')
      .insert([
        {
          age: 10,
          'class of worker': null,
          'industry code': null,
          'occupation code': null,
          education: null,
          'wage per hour': null,
          'last education': null,
          'marital status': null,
          'major industry code': null,
          'major occupation code': null,
          mace: null,
          hispanice: null,
          sex: null,
          'member of labor': null,
          'reason for unemployment': null,
          fulltime: null,
          'capital gain': null,
          'capital loss': null,
          dividends: null,
          'income tax liability': null,
          'previous residence region': null,
          'previous residence state': null,
          'household-with-family': null,
          'household-simple': null,
          weight: null,
          'msa-change': null,
          'reg-change': null,
          'within-reg-change': null,
          'lived-here': null,
          'migration prev res in sunbelt': null,
          'num persons worked for employer': null,
          'family members under 118': null,
          'father birth country': null,
          'mother birth country': null,
          'birth country': null,
          citizenship: null,
          'own business or self employed': null,
          'fill questionnaire for veteran\'s admin': null,
          'veterans benefits': null,
          'weeks worked in year': null,
          year: null,
          'salary range': '10',
        },
        {
          age: 20,
          'class of worker': null,
          'industry code': null,
          'occupation code': null,
          education: null,
          'wage per hour': null,
          'last education': null,
          'marital status': null,
          'major industry code': null,
          'major occupation code': null,
          mace: null,
          hispanice: null,
          sex: null,
          'member of labor': null,
          'reason for unemployment': null,
          fulltime: null,
          'capital gain': null,
          'capital loss': null,
          dividends: null,
          'income tax liability': null,
          'previous residence region': null,
          'previous residence state': null,
          'household-with-family': null,
          'household-simple': null,
          weight: null,
          'msa-change': null,
          'reg-change': null,
          'within-reg-change': null,
          'lived-here': null,
          'migration prev res in sunbelt': null,
          'num persons worked for employer': null,
          'family members under 118': null,
          'father birth country': null,
          'mother birth country': null,
          'birth country': null,
          citizenship: null,
          'own business or self employed': null,
          'fill questionnaire for veteran\'s admin': null,
          'veterans benefits': null,
          'weeks worked in year': null,
          year: null,
          'salary range': '20',
        },
        {
          age: 40,
          'class of worker': null,
          'industry code': null,
          'occupation code': null,
          education: null,
          'wage per hour': null,
          'last education': null,
          'marital status': null,
          'major industry code': null,
          'major occupation code': null,
          mace: null,
          hispanice: null,
          sex: null,
          'member of labor': null,
          'reason for unemployment': null,
          fulltime: null,
          'capital gain': null,
          'capital loss': null,
          dividends: null,
          'income tax liability': null,
          'previous residence region': null,
          'previous residence state': null,
          'household-with-family': null,
          'household-simple': null,
          weight: null,
          'msa-change': null,
          'reg-change': null,
          'within-reg-change': null,
          'lived-here': null,
          'migration prev res in sunbelt': null,
          'num persons worked for employer': null,
          'family members under 118': null,
          'father birth country': null,
          'mother birth country': null,
          'birth country': null,
          citizenship: null,
          'own business or self employed': null,
          'fill questionnaire for veteran\'s admin': null,
          'veterans benefits': null,
          'weeks worked in year': null,
          year: null,
          'salary range': '20',
        },
        {
          age: 30,
          'class of worker': null,
          'industry code': null,
          'occupation code': null,
          education: null,
          'wage per hour': null,
          'last education': null,
          'marital status': null,
          'major industry code': null,
          'major occupation code': null,
          mace: null,
          hispanice: null,
          sex: null,
          'member of labor': null,
          'reason for unemployment': null,
          fulltime: null,
          'capital gain': null,
          'capital loss': null,
          dividends: null,
          'income tax liability': null,
          'previous residence region': null,
          'previous residence state': null,
          'household-with-family': null,
          'household-simple': null,
          weight: null,
          'msa-change': null,
          'reg-change': null,
          'within-reg-change': null,
          'lived-here': null,
          'migration prev res in sunbelt': null,
          'num persons worked for employer': null,
          'family members under 118': null,
          'father birth country': null,
          'mother birth country': null,
          'birth country': null,
          citizenship: null,
          'own business or self employed': null,
          'fill questionnaire for veteran\'s admin': null,
          'veterans benefits': null,
          'weeks worked in year': '10 weeks',
          year: null,
          'salary range': null,
        },
      ])// eslint-disable-line
    );
  })
  .catch((err) => { console.log(err); }); // eslint-disable-line
};

